# Generated by Django 5.2.4 on 2025-08-02 09:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('phone_num', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'bank',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('account_registered_at', models.DateTimeField(default=datetime.datetime(2025, 8, 2, 18, 56, 21, 966409))),
                ('account_updated_at', models.DateTimeField(default=datetime.datetime(2025, 8, 2, 18, 56, 21, 966409))),
                ('bank_id', models.ForeignKey(db_column='bank_id', on_delete=django.db.models.deletion.CASCADE, to='PaymentApp.bank')),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_day', models.DateTimeField()),
                ('payed_place', models.CharField(max_length=30)),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('account_id', models.ForeignKey(db_column='account_id', on_delete=django.db.models.deletion.CASCADE, related_name='rnaccid', to='PaymentApp.account')),
                ('account_number', models.ForeignKey(db_column='account_number', on_delete=django.db.models.deletion.CASCADE, related_name='rnaccnum', to='PaymentApp.account', to_field='account_number')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
